CXX      = g++
CXXFLAGS = -std=c++23 -Wall -Wextra -g -I. -iquote kernel

NET_SRCS = kernel/net/ethernet.cc \
           kernel/net/arp.cc \
           kernel/net/ip.cc \
           kernel/net/tcp.cc

TEST_SRCS = kernel/test/mock_nic.cc \
            kernel/test/stub_kernel.cc \
            kernel/test/net_test.cc

all: test

test: net_test
	@echo "Running network stack tests..."
	@./net_test

net_test: $(NET_SRCS) $(TEST_SRCS)
	$(CXX) $(CXXFLAGS) -o $@ $^
	@echo "Compiled net_test"

clean:
	rm -f net_test

.PHONY: all test clean
